
spring:
  profiles:
    active: test
  main:
    banner-mode: off

#Defaults
name: product-service
management:
  context-path: /public
  info:
    git:
      mode: full
  health:
    defaults:
      enabled: false
server:
  contextPath: /v1/api

---
#Dev
spring:
  profiles: dev
product:
  logging:
    access:
      enabled: false
spring:
  datasource:
    #url: jdbc:mysql://10.167.199.70:6603/products_dev
    url: jdbc:mysql://localhost:3306/product_dev?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    #test-on-borrow: true
    #validation-query: SELECT 1 FROM dual

---
#QA
spring:
  profiles: qa
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

#PROD
---
spring:
  profiles: prod

#Test
---
spring:
  profiles: test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_dev?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

