/* Product table definition */
DROP TABLE IF EXISTS product;
CREATE TABLE product(
  productId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  description VARCHAR(200) NOT NULL,
  buyPrice DECIMAL(3,2) NOT NULL,
  salePrice DECIMAL(3,2) NULL,
  wholeSalePrice DECIMAL(3,2) NULL,
  onSale TINYINT(6) DEFAULT '0',
  unitInStock SMALLINT(6) DEFAULT '0',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);